config/routes.rb
Masturbate::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    member do
      get :profile
    end
  end
  resources :comments
  resources :boards
  resources :stocks do
    member do
      get :register
    end
  end
  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :title

  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :board_id, :contents, :stock_id, :user_id
  belongs_to :user
  belongs_to :board
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  attr_accessible :code, :high, :low, :market, :name, :opening, :previousprice, :previousvolume, :price, :volume, :chart


  has_many :comments
  def self.convert(url)
    begin
      page = open(url)
    rescue OpenURI::HTTPError
      return
    end
    doc = Nokogiri::HTML(page.read, nil, 'utf-8')
  end
end

app/models/stock_user_relation.rb
class StockUserRelation < ActiveRecord::Base
  attr_accessible :stock_id, :user_id
  belongs_to :user
  belongs_to :stock
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username, :image, :remote_image_url
  mount_uploader :image, ImageUploader

  has_many :stock_user_relations
  has_many :stocks, through: :stock_user_relations, source: :stock

  has_many :comments
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    user_path(current_user)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def after_sign_up_path_for(resource)                                                     
		after_sign_in_path_for(resource)                                                
	end
	def after_inactive_sign_up_path_for(resource)
		welcome_path
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

	def register
		current_user.stocks << Stock.find(params[:id])
		redirect_to :back
	end

	def show
		@stock = Stock.find(params[:id])
	end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    unless @user
      redirect_to root_path
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
   
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user 
      redirect_to user_path(current_user)
      return 
    end
    @user = User.new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginOnly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<%= render partial: 'users/timeline_header', locals: {user: current_user} %>
	<% else %>
		<%= render partial: 'welcome/welcome_header' %>
	<% end %>
	<div id="container"> 
		<div class="inside">
			<%= yield %>
		</div>
	<div>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%= stock.name %></td>
    <td><%= link_to 'Show', stock %></td>
    <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
    <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stock.name %>
</p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.file_field :image %>
  </div>
      
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_timeline_header.html.erb
<div id="timeline_header" class="clearfix">
  <div id="timeline_header_inner">
    <div id="logo">
      <%= link_to "STOCK PIN", "/welcome/index", :class => "serif" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<%= @user.email %>のプロフィールページ

app/views/users/show.html.erb
<div class="stock_inner">
  stock
  <% Stock.limit(5).each do |stock| %>
  	<%= image_tag(stock.chart)%><br>
  	<%= link_to stock.name, stock_path(stock) %>:<%= image_tag("star.jpeg")%><%= link_to "お気に入り登録", register_stock_path(id: stock.id) %><br>
    <table class="">
      <tr><td>現在株価</td><td class="font_blod stock_table_td_align"><%= stock.price %></td></tr>
      <tr><td>前日比</td><td class="stock_table_td_align"><%= stock.code %></td></tr>
      <tr><td>出来高</td><td class="stock_table_td_align"><%= stock.volume %></td></tr>
      <% stock.comments.each do |comment| %>
        <div class="comment clearfix">
          <div class="comment_image">
            <%= image_tag(comment.user.image_url(:thumb),{width: "30px", height: "30px"}) if comment.user.image? %>
          </div>
          <div class="comment_contents">
            <p class="comment_username">
              <%= link_to comment.user.email, profile_user_path(comment.user) %>
            </p>
            <p class="contents">
              <%= comment.contents %>
            </p>
              <p class="GrayColor time_info">
                <%= time_ago_in_words(comment.created_at) %>前&nbsp;
              </p>
          </div>
        </div>
      <% end %>
    </table>
    <% @comment = Comment.new %>
    <%= form_for(@comment) do |f| %>
      <div class="field">
        <%= f.label :contents %><br />
        <%= f.text_field :contents %>
      </div>
      <%= f.hidden_field :stock_id, value: stock.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="actions">
        <%= f.submit 'コメント', disable_with: 'コメント中' %>
      </div>
    <% end %>
  <% end %>
  <p>
    <b>Username:</b>
    <%= current_user.email %>
  </p>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

</div>
<div class="follow_inner">
  <% Stock.limit(10).each do |stock| %>
    <%= image_tag(stock.chart)%><br>
    <%= link_to stock.name, stock_path(stock) %>:<%= image_tag("star.jpeg")%><%= link_to "お気に入り登録", register_stock_path(id: stock.id) %><br>
    <table class="">
      <tr><td>現在株価</td><td class="font_blod stock_table_td_align"><%= stock.price %></td></tr>
      <tr><td>前日比</td><td class="stock_table_td_align"><%= stock.code %></td></tr>
      <tr><td>出来高</td><td class="stock_table_td_align"><%= stock.volume %></td></tr>
      <% stock.comments.each do |comment| %>
        <div class="comment clearfix">
          <div class="comment_image">
            <%= image_tag(comment.user.image_url(:thumb),{width: "30px", height: "30px"}) if comment.user.image? %>
          </div>
          <div class="comment_contents">
            <p class="comment_username">
              <%= link_to comment.user.email, profile_user_path(comment.user) %>
            </p>
            <p class="contents">
              <%= comment.contents %>
            </p>
              <p class="GrayColor time_info">
                <%= time_ago_in_words(comment.created_at) %>前&nbsp;
              </p>
          </div>
        </div>
      <% end %>
    </table>
    <% @comment = Comment.new %>
    <%= form_for(@comment) do |f| %>
      <div class="field">
        <%= f.label :contents %><br />
        <%= f.text_field :contents %>
      </div>
      <%= f.hidden_field :stock_id, value: stock.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="actions">
        <%= f.submit 'コメント', disable_with: 'コメント中' %>
      </div>
    <% end %>
  <% end %>
  <p>
    <b>Username:</b>
    <%= current_user.email %>
  </p>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>

</div>

app/views/welcome/_welcome_header.html.erb
<div id="welcome_header" class="clearfix">
  <div id="welcome_header_inner">
    <div id="logo">
      <%= link_to "STOCK PIN", "/welcome/index", :class => "serif" %>
    </div>
    <ul>
      <%= form_for(:user, :url => session_path(:user)) do |f| %>
        <li>
          <%= f.email_field :email, placeholder: "ユーザネーム", class: "text_input login_form" %>&nbsp;&nbsp;
          <%= f.password_field :password, placeholder: "パスワード", :class=>"text_input login_form" %>
          <%= f.submit "ログイン", :class=>"login_button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="content" class="clearfix">
	<div id="left">
		<div id="vision" class="serif">
			Pinterest For Stock
		</div>
	</div>
	<div id="right">
		<div id="sign_up">
			<p id="topic">
				アカウント登録
			</p>
			<p id="detail">
				あああ
			</p>
			<div id="reg_form_container">
				<div id="reg_form">
					<%= form_for(@user) do |f| %>
							<div class="field">
								<%= f.email_field :email, :placeholder=>"メールアドレス", :class=>"text_input mail_form" %>
							</div>
							<div class="field">

								<%= f.password_field :password, :placeholder=>"パスワード", :class=>"text_input pass_form" %>&nbsp;&nbsp;<%= f.password_field :password_confirmation, :placeholder=>"パスワード（再入力）", :class=>"text_input pass_form" %>
							</div>
							<div class="reg_button_wrap">
								<%= f.submit "アカウント登録", :class=>"reg_button" %>
							</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>